[package]
name = "hack_jack_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1"
traitcast = "0.*"
inventory = "0.1.*"
traitcast_core = "0.2.*"
